### ISSUE TITLE
Can't connect to RabbitMQ server (local)

### ISSUE THREAD

**Issue by Astuce-Julian** [NinevaStudios/mqtt-utilities-unreal#10]
Hi, 
I have heard great things about this plugin but I am having a hard time connecting to RabbitMQ. I have a local RabbitMQ server setup and confirmed it is working properly using a custom C# application. But whenever I try to connect to my server using this plugin, I constantly get the error in Unreal _Error: MQTT => Connection error: The connection was lost._

I have set the proper username and password as well as the url and port (checked 1000 times). I get this issue in your test scene as well when inputting my server configuration information so it's not an issue in my logic. Are there any specific settings needed on the RabbitMQ server (virtual host, queue settings, etc) for the plugin to connect?
Any ideas?

**Comment by Astuce-Julian** [comment]
FYI I am running in UE4.26 on Windows

**Comment by mosaicchen** [comment]
@Astuce-Julian Hi, I have the same problem as you. Have you solved it yet?

**Comment by Astuce-Julian** [comment]
@mosaicchen What worked for me was changing the communication protocol being used by the RabbitMQ server. By default it was set to AMQP. My server admin added a connection that uses MQTT and the plugin was working properly afterwards (sadly I can't help with that as I am not familiar with RabbitMQ server management).

**Comment by mosaicchen** [comment]
> 

Thank you very much. Unfortunately I am just a Unreal Client developer and I have no permission to modify the RabbitMQ server. Maybe I should find some new solutions.
