### ISSUE TITLE
Unable to package the project into H5 or windows with this plugin

### ISSUE THREAD

**Issue by Akun9527** [NinevaStudios/mqtt-utilities-unreal#11]
Hello and thanks for the great work you guys have done here.

Everything works fine inside the UE4 editor play mode. But when I try to package this project into H5 format, I had this issue:
And my UE4 engine version is 4.23.1. Don't know whether it's some compatiable issue.

> PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Mqtt Message  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Message  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Topic  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] No Struct in  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Publish . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Target  no longer exists on node  Publish . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Message  no longer exists on node  Publish . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "Publish" in 'LaunchPad_Blueprint'.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Subscribe . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Subscribe . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Target  no longer exists on node  Subscribe . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Topic  specifying non-default value no longer exists on node  Subscribe . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "Subscribe" in 'LaunchPad_Blueprint'.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Mqtt Connection Data  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Login  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Password  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] No Struct in  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Target  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Connection Data  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  On Connect Callback  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "Connect" in 'LaunchPad_Blueprint'.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Mqtt Client Config  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Host Url  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Port  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Warning: [Compiler LaunchPad_Blueprint] Input pin  Client Id  specifying non-default value no longer exists on node  Make <unknown struct> . Please refresh node or reset pin to default value to remove pin.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] No Struct in  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Config  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] In use pin  Return Value  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "CreateMqttClient" in 'LaunchPad_Blueprint'.
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Unknown structure to break for  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Unknown structure to break for  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
PackagingResults: Error: [Compiler LaunchPad_Blueprint] Unknown structure to break for  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint

> UATHelper: Packaging (HTML5):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint_C:ExecuteUbergraph_LaunchPad_Blueprint.K2Node_MakeStruct_MqttMessage'. Unknown structure.
UATHelper: Packaging (HTML5):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint_C:ExecuteUbergraph_LaunchPad_Blueprint.K2Node_MakeStruct_MqttClientConfig'. Unknown structure.
UATHelper: Packaging (HTML5):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint_C:ExecuteUbergraph_LaunchPad_Blueprint.K2Node_MakeStruct_MqttConnectionData'. Unknown structure.
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Mqtt Message  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] No Struct in  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Publish . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Target  no longer exists on node  Publish . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Message  no longer exists on node  Publish . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "Publish" in 'LaunchPad_Blueprint'.
UATHelper: Packaging (HTML5):   Make sure 'LaunchPad_Blueprint' has been compiled for  Publish from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Subscribe . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Target  no longer exists on node  Subscribe . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "Subscribe" in 'LaunchPad_Blueprint'.
UATHelper: Packaging (HTML5):   Make sure 'LaunchPad_Blueprint' has been compiled for  Subscribe from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Mqtt Connection Data  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Target  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Connection Data  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  On Connect Callback  no longer exists on node  Connect . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "Connect" in 'LaunchPad_Blueprint'.
UATHelper: Packaging (HTML5):   Make sure 'LaunchPad_Blueprint' has been compiled for  Connect from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Mqtt Client Config  no longer exists on node  Make <unknown struct> . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  <Unnamed>  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Config  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] In use pin  Return Value  no longer exists on node  Create Mqtt Client . Please refresh node or break links to remove pin. from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] Could not find a function named "CreateMqttClient" in 'LaunchPad_Blueprint'.
UATHelper: Packaging (HTML5):   Make sure 'LaunchPad_Blueprint' has been compiled for  Create Mqtt Client from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint
UATHelper: Packaging (HTML5):   LogInit: Display: LogBlueprint: Error: [Compiler LaunchPad_Blueprint] Unknown structure to break for  Make <unknown struct> from Source: /Game/SideScrollerBP/Blueprints/LaunchPad_Blueprint.LaunchPad_Blueprint

**Comment by lanyuxiao** [comment]
Same problems， Version 4.26,4.24.
Build windows exe.

**Comment by lanyuxiao** [comment]
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/StarterContent/BP/mqtt_BP.mqtt_BP_C:Array.Array'. Unknown structure.
LogUObjectGlobals: Warning: [AssetLog] C:\Users\dell\Desktop\anjie\ue4shiyanxiangmu\mqtt\Content\StarterContent\BP\mqtt_BP.uasset: 未能加载“{FileName}”：无法找到文件。
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/StarterContent/BP/mqtt_BP.mqtt_BP_C:NewVar_0'. Unknown structure.
LogUObjectGlobals: Warning: [AssetLog] C:\Users\dell\Desktop\anjie\ue4shiyanxiangmu\mqtt\Content\StarterContent\BP\mqtt_BP.uasset: 未能加载“{FileName}”：无法找到文件。
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/StarterContent/BP/mqtt_BP.mqtt_BP_C:GetConnectionData:MqttConnectionData'. Unknown structure.
LogUObjectGlobals: Warning: [AssetLog] C:\Users\dell\Desktop\anjie\ue4shiyanxiangmu\mqtt\Content\StarterContent\BP\mqtt_BP.uasset: 未能加载“{FileName}”：无法找到文件。
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/StarterContent/BP/mqtt_BP.mqtt_BP_C:GetConnectionData:K2Node_MakeStruct_MqttConnectionData'. Unknown structure.
LogUObjectGlobals: Warning: [AssetLog] C:\Users\dell\Desktop\anjie\ue4shiyanxiangmu\mqtt\Content\StarterContent\BP\mqtt_BP.uasset: 未能加载“{FileName}”：无法找到文件。
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/StarterContent/BP/mqtt_BP.mqtt_BP_C:GetClientConfigData:MqttClientConfig'. Unknown structure.
LogUObjectGlobals: Warning: [AssetLog] C:\Users\dell\Desktop\anjie\ue4shiyanxiangmu\mqtt\Content\StarterContent\BP\mqtt_BP.uasset: 未能加载“{FileName}”：无法找到文件。
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/StarterContent/BP/mqtt_BP.mqtt_BP_C:GetClientConfigData:K2Node_MakeStruct_MqttClientConfig'. Unknown structure.
LogUObjectGlobals: Warning: [AssetLog] C:\Users\dell\Desktop\anjie\ue4shiyanxiangmu\mqtt\Content\StarterContent\BP\mqtt_BP.uasset: 未能加载“{FileName}”：无法找到文件。
LogProperty: Error: FStructProperty::Serial

**Comment by tustanivsky** [comment]
Hi, this plugin doesn't support HTML5 - it works only for Win/Mac/Linux/iOS/Android.
