### ISSUE TITLE
Where to start recompiling for Unreal 5?

### ISSUE THREAD

**Issue by anselanza** [NinevaStudios/mqtt-utilities-unreal#14]
I'm new to Unreal, though I'm an experienced programmer (including C++, and MQTT specifically), and I'm not sure how to get this plugin working in Unreal 5.

If I add the plugin to a `Plugins/` folder in the root of my project, the Editor definitely picks up the plugin as expected, but I get the following errors:

<img width="264" alt="Screenshot 2022-04-07 at 16 08 29" src="https://user-images.githubusercontent.com/3015222/162218983-eb53a486-4fd1-4203-b339-f6d7dfb5806a.png">
Unsurprisingly, it complains about the engine version, but I click "Yes" to attempt to load it anyway...

<img width="272" alt="Screenshot 2022-04-07 at 16 08 34" src="https://user-images.githubusercontent.com/3015222/162219099-ede66c2d-7203-462c-b4dc-a3fa244853b0.png">

My project is called "SpatialForest". The editor has picked up that the MQTT Utilities plugin has not been compiled yet, which makes sense. Again, I click "yes" to attempt to compile the module (and its dependencies?)...

<img width="265" alt="Screenshot 2022-04-07 at 16 08 44" src="https://user-images.githubusercontent.com/3015222/162219327-242999d3-6c8d-498f-9721-5f10696d8fe0.png">

And now I can get no further. The Editor won't even open. The error suggests I should "manually compile" the plugin, but I have no idea how to do this. I'm on a Mac (M1 Pro) with Xcode installed (and Cmake, Clang, gcc, etc.) but I'm not familiar with Unreal's build system so I'm unclear where to even start recompiling manually?

**Comment by tustanivsky** [comment]
Hi, try to replace `using Tools.DotNETCommon;` in MqttUtilities.Build.cs wth something similar to this:
`
#if UE_5_0_OR_LATER
using EpicGames.Core;
#else
using Tools.DotNETCommon;
#endif
`
In UE5 some UBT-related functionality was moved to a different assembly and likely that is the main reason for this issue.

**Comment by anselanza** [comment]
Thanks for the tip.

Unfortunately this didn't seem to help.

Is there any way to get some output, error details from the compiling process? It's kind of hard to figure out what to do when there's no feedback other than the building failing with an "error" and then the project/editor just doesn't even open!

**Comment by anselanza** [comment]
Doesn't seem to be any trace of logs here:
<img width="338" alt="Screenshot 2022-04-07 at 17 41 57" src="https://user-images.githubusercontent.com/3015222/162239947-9c1ef9e9-d8f9-44ce-81bd-a12489a287a4.png">

**Comment by tustanivsky** [comment]
I've noticed that there is a minor issue in `Mac/MqttRunnable.cpp` - in class constructor fields initialization order doesn't match with their declaration order in `Mac/MqttRunnable.h`
It looks that for some reason UE5 interprets this warning as an error. Try to change the fields initialization order and give it another shot

<img width="501" alt="NinevaPlayground_–_MqttRunnable_cpp-2" src="https://user-images.githubusercontent.com/3168564/162253377-6bb52d03-3b2d-4437-aa7b-b949998d5bfb.png">

**Comment by tustanivsky** [comment]
Hey there, just wanted to let you know that I've just pushed some fixes to `master` so you can try it out once again

**Comment by anselanza** [comment]
Wow, looks like it succeeded!

The project has opened, at least. Now time to get it all working.

Thank you so much @tustanivsky !

**Comment by bconrad98** [comment]
I've pulled the latest from master and I'm getting a similar issue in Windows.
