### ISSUE TITLE
Can we use this as a Queue

### ISSUE THREAD

**Issue by mavisakal** [NinevaStudios/mqtt-utilities-unreal#9]
Hi, 
There is no message queue plugin for UE4 . Is there a way to use this as a queue mechanism? I mean in a queue mechanism a message goes to one and only one possible subscriber. 
Thanks

**Comment by tustanivsky** [comment]
Hello,
This plugin acts as a simple MQTT client for UE4 and doesn't provide the functionality you've described above.
